# This file was adapted from the SE-EDU Brownfield Project: https://github.com/nus-cs2103-AY2324S1/tp

name: CI

on: [push, pull_request]

jobs:
    build:
        strategy:
            matrix:
                platform: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.platform }}

        steps:
            - name: Set up repository
              uses: actions/checkout@main

            - name: Set up repository
              uses: actions/checkout@main
              with:
                  ref: main

            - name: Merge to main
              run: git checkout --progress --force ${{ github.sha }}

            - name: Run ESLint
              run: npm run lint

            - name: Run repository-wide tests
              if: runner.os == 'Linux'
              working-directory: ${{ github.workspace }}/.github
              run: ./run-checks.sh

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
